In [72]:
import pandas as pd

df = pd.read_csv('Dataset/speakers_all.csv',delimiter=',')
unique_countries = df['country'].nunique()
country_counts = df['country'].value_counts()

print(country_counts)

country
usa         393
china        88
uk           67
india        59
canada       54
           ... 
namibia       1
romanian      1
burundi       1
rwanda        1
benin         1
Name: count, Length: 176, dtype: int64


In [73]:
df.head()

age  age_onset              birthplace  filename native_language   sex  \
0  24.0       12.0         koussi, senegal   balanta         balanta  male   
1  18.0       10.0          buea, cameroon  cameroon        cameroon  male   
2  48.0        8.0  hong, adamawa, nigeria  fulfulde        fulfulde  male   
3  42.0       42.0   port-au-prince, haiti   haitian         haitian  male   
4  40.0       35.0   port-au-prince, haiti   haitian         haitian  male   

   speakerid   country  file_missing?  Unnamed: 9  Unnamed: 10 Unnamed: 11  
0        788   senegal           True         NaN          NaN         NaN  
1       1953  cameroon           True         NaN          NaN         NaN  
2       1037   nigeria           True         NaN          NaN         NaN  
3       1165     haiti           True         NaN          NaN         NaN  
4       1166     haiti           True         NaN          NaN         NaN

In [74]:
countries_to_continents = {
    "afghanistan": "Asia",
    "armenia": "Asia",
    "azerbaijan": "Asia",
    "bahrain": "Asia",
    "bangladesh": "Asia",
    "bhutan": "Asia",
    "brunei": "Asia",
    "cambodia": "Asia",
    "china": "Asia",
    "cyprus": "Asia",
    "east timor": "Asia",
    "egypt": "Asia",
    "georgia": "Asia",
    "india": "Asia",
    "indonesia": "Asia",
    "iran": "Asia",
    "iraq": "Asia",
    "israel": "Asia",
    "japan": "Asia",
    "jordan": "Asia",
    "kazakhstan": "Asia",
    "kuwait": "Asia",
    "kyrgyzstan": "Asia",
    "laos": "Asia",
    "lebanon": "Asia",
    "malaysia": "Asia",
    "maldives": "Asia",
    "mongolia": "Asia",
    "myanmar": "Asia",
    "nepal": "Asia",
    "north korea": "Asia",
    "oman": "Asia",
    "pakistan": "Asia",
    "palestine": "Asia",
    "philippines": "Asia",
    "qatar": "Asia",
    "russia": "Asia",
    "saudi arabia": "Asia",
    "singapore": "Asia",
    "south korea": "Asia",
    "sri lanka": "Asia",
    "syria": "Asia",
    "taiwan": "Asia",
    "tajikistan": "Asia",
    "thailand": "Asia",
    "turkey": "Asia",
    "turkmenistan": "Asia",
    "united arab emirates": "Asia",
    "uzbekistan": "Asia",
    "vietnam": "Asia",
    "yemen": "Asia",
    "albania": "Europe",
    "andorra": "Europe",
    "austria": "Europe",
    "belarus": "Europe",
    "belgium": "Europe",
    "bosnia and herzegovina": "Europe",
    "bulgaria": "Europe",
    "croatia": "Europe",
    "cyprus": "Europe",
    "czech republic": "Europe",
    "denmark": "Europe",
    "estonia": "Europe",
    "finland": "Europe",
    "france": "Europe",
    "germany": "Europe",
    "greece": "Europe",
    "hungary": "Europe",
    "iceland": "Europe",
    "ireland": "Europe",
    "italy": "Europe",
    "kosovo": "Europe",
    "latvia": "Europe",
    "liechtenstein": "Europe",
    "lithuania": "Europe",
    "luxembourg": "Europe",
    "north macedonia": "Europe",
    "malta": "Europe",
    "moldova": "Europe",
    "monaco": "Europe",
    "montenegro": "Europe",
    "netherlands": "Europe",
    "norway": "Europe",
    "poland": "Europe",
    "portugal": "Europe",
    "romania": "Europe",
    "russia": "Europe",
    "san marino": "Europe",
    "serbia": "Europe",
    "slovakia": "Europe",
    "slovenia": "Europe",
    "spain": "Europe",
    "sweden": "Europe",
    "switzerland": "Europe",
    "turkey": "Europe",
    "ukraine": "Europe",
    "united kingdom": "Europe",
    "argentina": "South America",
    "bolivia": "South America",
    "brazil": "South America",
    "chile": "South America",
    "colombia": "South America",
    "ecuador": "South America",
    "guyana": "South America",
    "paraguay": "South America",
    "peru": "South America",
    "suriname": "South America",
    "uruguay": "South America",
    "venezuela": "South America",
    "canada": "North America",
    "usa": "North America",
    "mexico": "North America",
    "belize": "North America",
    "costa rica": "North America",
    "el salvador": "North America",
    "guatemala": "North America",
    "honduras": "North America",
    "nicaragua": "North America",
    "panama": "North America",
    "antigua and barbuda": "North America",
    "bahamas": "North America",
    "barbados": "North America",
    "cuba": "North America",
    "dominica": "North America",
    "dominican republic": "North America",
    "grenada": "North America",
    "haiti": "North America",
    "jamaica": "North America",
    "saint kitts and nevis": "North America",
    "saint lucia": "North America",
    "saint vincent and the grenadines": "North America",
    "trinidad and tobago": "North America",
    "algeria": "Africa",
    "angola": "Africa",
    "benin": "Africa",
    "botswana": "Africa",
    "burkina Faso": "Africa",
    "burundi": "Africa",
    "cabo verde": "Africa",
    "cameroon": "Africa",
    "central african republic": "Africa",
    "chad": "Africa",
    "comoros": "Africa",
    "democratic republic of the congo": "Africa",
    "republic of the congo": "Africa",
    "côte d'Ivoire": "Africa",
    "djibouti": "Africa",
    "egypt": "Africa",
    "equatorial guinea": "Africa",
    "eritrea": "Africa",
    "eswatini": "Africa",
    "ethiopia": "Africa",
    "gabon": "Africa",
    "gambia": "Africa",
    "ghana": "Africa",
    "guinea": "Africa",
    "guinea-bissau": "Africa",
    "ivory coast":"Africa",
    "kenya": "Africa",
    "lesotho": "Africa",
    "liberia": "Africa",
    "libya": "Africa",
    "madagascar": "Africa",
    "malawi": "Africa",
    "mali": "Africa",
    "mauritania": "Africa",
    "mauritius": "Africa",
    "morocco": "Africa",
    "mozambique": "Africa",
    "namibia": "Africa",
    "niger": "Africa",
    "nigeria": "Africa",
    "rwanda": "Africa",
    "são tomé and príncipe": "Africa",
    "senegal": "Africa",
    "seychelles": "Africa",
    "sierra leone": "Africa",
    "somalia": "Africa",
    "south africa": "Africa",
    "south sudan": "Africa",
    "sudan": "Africa",
    "tanzania": "Africa",
    "togo": "Africa",
    "tunisia": "Africa",
    "uganda": "Africa",
    "zambia": "Africa",
    "zimbabwe": "Africa",
    "antarctica": "Antarctica",
    "australia": "Oceania",
    "fiji": "Oceania",
    "kiribati": "Oceania",
    "marshall islands": "Oceania",
    "micronesia, federated states of": "Oceania",
    "nauru": "Oceania",
    "new zealand": "Oceania",
    "palau": "Oceania",
    "papua new guinea": "Oceania",
    "samoa": "Oceania",
    "solomon islands": "Oceania",
    "tonga": "Oceania",
    "tuvalu": "Oceania",
    "vanuatu": "Oceania"
}

In [75]:
print(df['country'].head())
print(len(countries_to_continents))

0     senegal
1    cameroon
2     nigeria
3       haiti
4       haiti
Name: country, dtype: object
198


In [76]:
#type(df['file_missing?'])
df['file_missing?']

0        True
1        True
2        True
3        True
4        True
        ...  
2165    False
2166    False
2167    False
2168    False
2169    False
Name: file_missing?, Length: 2170, dtype: bool

In [77]:
df.shape

(2170, 12)

In [78]:
df.drop(df[df['file_missing?'] == True].index, inplace=True)


In [79]:
df.head()
df.shape

(2138, 12)

In [80]:
X = df['filename']

In [81]:
# filtered_dict = {country: countries_to_continents[country] for country in y_labels if country in countries_to_continents}
# continents_list = [countries_to_continents.get(country, 'Other') for country in countries_to_continents]
# yc_labels = list(filtered_dict.values())
# df = pd.DataFrame({"country": ["cameroon", "senegal"]})
df["continents"] = df["country"].map(countries_to_continents)
y_labels = df['continents']

In [82]:
type(df['continents'])

pandas.core.series.Series

In [83]:
# Assuming 'df' is your DataFrame and 'continents' is the column name
continent_counts = df['continents'].value_counts()

# Display the count of unique values in the 'continents' column
print(continent_counts)


continents
Asia             566
North America    530
Europe           505
Africa           217
South America    125
Oceania           50
Name: count, dtype: int64


In [84]:
print(X.shape)
print(y_labels.shape)
y_labels

(2138,)
(2138,)


32             Africa
33             Africa
34             Africa
35             Africa
36             Africa
            ...      
2165           Africa
2166           Africa
2167           Africa
2168    North America
2169           Africa
Name: continents, Length: 2138, dtype: object

In [85]:
# from sklearn.model_selection import train_test_split

# df = df.sample(frac=1, random_state=42)  # 'frac=1' shuffles the entire dataset

# # Perform an 80/20 split for training and test
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [86]:
import pandas as pd

base_path = 'Dataset/recordings/'

X = base_path + X + '.mp3'
# X_test = base_path + X_test + '.mp3'

X_image_paths = X.tolist()
# X_test_image_paths = X_test.tolist()


In [87]:
print(X_image_paths[:5])
# print(X_test_image_paths[:5])

['Dataset/recordings/afrikaans1.mp3', 'Dataset/recordings/afrikaans2.mp3', 'Dataset/recordings/afrikaans3.mp3', 'Dataset/recordings/afrikaans4.mp3', 'Dataset/recordings/afrikaans5.mp3']


In [88]:
import librosa
import numpy as np

# Function to extract features from audio file
def extract_features(file_path):
    try:
        # Load audio file
        y, sr = librosa.load(file_path)
        
        # Extract MFCCs (Mel-frequency cepstral coefficients)
        mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
        mfccs_mean = np.mean(mfccs, axis=1)
        
        return mfccs_mean  # Return the extracted features (MFCCs mean)
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return None

# Extract features for each audio file in X_train_image_paths
extracted_features = []
for file_path in X_image_paths:
    features = extract_features(file_path)
    if features is not None:
        extracted_features.append(features)

# Convert the list of features to a NumPy array
X_image_features = np.array(extracted_features)

In [89]:
print(X_image_features)

[[-2.80801056e+02  9.92121658e+01  1.62540607e+01 ... -5.14061308e+00
  -2.73235774e+00 -1.15841284e+01]
 [-2.47785660e+02  9.27956161e+01  7.03312778e+00 ... -1.42139807e+01
  -1.34980392e+00 -6.84289598e+00]
 [-2.97333496e+02  1.09309593e+02  4.86944342e+00 ... -2.04761243e+00
  -6.17281675e+00 -9.02794838e+00]
 ...
 [-3.78120209e+02  1.26679924e+02  1.61770077e+01 ... -2.81823087e+00
  -9.12053776e+00 -6.03319788e+00]
 [-3.08208038e+02  1.27284134e+02 -2.40374565e+01 ... -8.25175571e+00
  -8.97601318e+00  3.13905805e-01]
 [-2.54454681e+02  8.36123657e+01 -7.57016230e+00 ... -8.22624207e+00
  -8.20982742e+00 -4.99016237e+00]]


In [90]:
y_labels.shape

(2138,)

In [91]:
print(type(y_labels))
y_labels_array = y_labels.values  # Convert Series to a NumPy array
y_labels = np.reshape(y_labels_array, (y_labels.shape[0], -1))

<class 'pandas.core.series.Series'>


In [92]:
y_labels[:6]

array([['Africa'],
       ['Africa'],
       ['Africa'],
       ['Africa'],
       ['Africa'],
       ['Africa']], dtype=object)

In [93]:
y_labels.shape, df['continents'].shape

((2138, 1), (2138,))

In [94]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
y_encoded_data = encoder.fit_transform(y_labels)

y_encoded_data.shape
print(y_encoded_data)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [95]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_image_features, y_encoded_data, test_size=0.2, random_state=42)

In [96]:
print(X_train.shape)
print(y_train.shape)

print(y_train)

(1710, 13)
(1710, 7)
[[0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [97]:
"""#y_train = np.reshape(y_train, -1)
y_train = np.array(y_train)
y_train.shape"""

y_train = np.argmax(y_train, axis=1)


In [98]:
y_train.shape

(1710,)

In [99]:
"""# Example of replacing NaN values with mean (for demonstration purposes)
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)
# y_train_imputed = imputer.fit_transform(y_train)

print(X_train.shape)
print(X_train)
"""

"# Example of replacing NaN values with mean (for demonstration purposes)\nfrom sklearn.impute import SimpleImputer\n\nimputer = SimpleImputer(strategy='mean')\nX_train_imputed = imputer.fit_transform(X_train)\n# y_train_imputed = imputer.fit_transform(y_train)\n\nprint(X_train.shape)\nprint(X_train)\n"

In [128]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Initialize the SVM classifier
svm_classifier = SVC(kernel='poly', C=1.0, gamma='scale')  # You can adjust hyperparameters

# Train the model on the training set
svm_classifier.fit(X_train, y_train)

SVC(kernel='poly')

In [129]:
# Make predictions on the test set
predictions = svm_classifier.predict(X_test)

In [130]:
predictions

array([1, 3, 3, 3, 1, 1, 1, 3, 2, 1, 3, 3, 1, 2, 2, 3, 3, 1, 1, 3, 1, 1,
       2, 3, 3, 3, 1, 1, 3, 3, 3, 1, 3, 3, 1, 3, 1, 3, 3, 3, 3, 1, 1, 3,
       1, 1, 1, 1, 3, 1, 3, 3, 3, 1, 3, 1, 3, 3, 1, 2, 1, 1, 3, 3, 3, 1,
       2, 3, 3, 1, 3, 1, 1, 1, 3, 1, 3, 1, 3, 1, 1, 3, 2, 1, 3, 3, 2, 1,
       1, 3, 1, 1, 3, 3, 3, 1, 1, 1, 2, 3, 1, 1, 2, 1, 3, 1, 1, 1, 1, 2,
       1, 3, 3, 3, 3, 1, 2, 1, 3, 1, 1, 2, 3, 3, 3, 3, 1, 2, 3, 1, 3, 2,
       3, 3, 2, 1, 1, 3, 3, 1, 3, 2, 3, 1, 3, 1, 1, 2, 3, 3, 3, 3, 3, 3,
       1, 3, 3, 1, 1, 2, 3, 3, 1, 1, 3, 2, 3, 3, 3, 1, 3, 1, 1, 1, 3, 1,
       3, 3, 3, 3, 1, 1, 2, 3, 3, 3, 3, 1, 1, 1, 3, 3, 3, 3, 1, 1, 3, 3,
       1, 1, 3, 1, 1, 1, 1, 3, 1, 3, 3, 1, 3, 3, 1, 3, 1, 3, 3, 3, 1, 3,
       1, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 3, 1, 3, 1, 3, 1, 1, 3, 1, 1, 1,
       3, 3, 3, 3, 1, 3, 1, 1, 1, 2, 3, 1, 2, 1, 3, 3, 2, 3, 1, 3, 1, 3,
       1, 1, 1, 1, 1, 3, 1, 1, 1, 3, 3, 3, 3, 3, 1, 1, 3, 2, 3, 2, 1, 3,
       3, 1, 1, 3, 3, 3, 3, 3, 1, 3, 1, 3, 3, 3, 1,

In [131]:
# y_test = np.argmax(y_test, axis=1)
y_test

array([1, 3, 2, 2, 0, 2, 1, 5, 1, 3, 6, 2, 2, 2, 2, 3, 1, 1, 3, 2, 5, 2,
       4, 1, 2, 5, 1, 3, 3, 1, 0, 3, 2, 1, 0, 3, 1, 3, 5, 2, 3, 3, 6, 1,
       0, 2, 1, 2, 0, 1, 6, 1, 3, 1, 3, 2, 1, 1, 3, 2, 2, 6, 1, 1, 1, 0,
       3, 0, 6, 1, 1, 1, 1, 3, 3, 0, 3, 2, 5, 1, 1, 2, 0, 2, 1, 0, 0, 2,
       2, 3, 0, 5, 2, 2, 3, 1, 4, 3, 2, 1, 0, 6, 2, 0, 2, 2, 3, 2, 2, 5,
       3, 2, 3, 3, 6, 2, 5, 1, 1, 2, 0, 6, 6, 1, 1, 3, 1, 2, 1, 1, 2, 2,
       3, 6, 2, 1, 2, 1, 3, 1, 2, 1, 3, 0, 3, 1, 2, 3, 2, 3, 3, 3, 3, 6,
       3, 3, 2, 2, 1, 1, 4, 3, 3, 3, 2, 3, 3, 2, 3, 2, 5, 1, 3, 1, 3, 3,
       0, 3, 6, 2, 1, 6, 2, 3, 1, 1, 3, 5, 6, 3, 1, 5, 3, 2, 3, 1, 4, 3,
       0, 0, 1, 0, 6, 1, 5, 2, 1, 3, 3, 1, 6, 5, 3, 3, 6, 5, 3, 6, 1, 3,
       6, 0, 1, 1, 0, 2, 3, 3, 6, 1, 2, 2, 1, 1, 0, 1, 1, 2, 3, 6, 3, 2,
       5, 3, 2, 1, 1, 2, 2, 2, 3, 3, 2, 2, 2, 1, 3, 3, 2, 1, 1, 1, 6, 3,
       4, 2, 6, 1, 2, 6, 2, 0, 5, 2, 1, 3, 1, 3, 1, 2, 3, 5, 3, 1, 2, 3,
       3, 1, 4, 2, 6, 2, 1, 1, 6, 3, 3, 1, 3, 1, 1,

In [132]:
from sklearn.metrics import f1_score, recall_score, accuracy_score

accuracy = accuracy_score(predictions, y_test) 
print("Test Accuracy: %.2f%%" %(accuracy*100.0))

f1 = f1_score(y_test, predictions, average='micro')  
print("F1 Score: %.2f" % f1)

recall = recall_score(y_test, predictions, average='micro')
print("Recall: %.2f" % recall)

Test Accuracy: 33.64%
F1 Score: 0.34
Recall: 0.34
